services:
  - type: web
    name: churn-fastapi
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn fastapi_app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
  - type: web
    name: churn-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_dashboard.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: "/opt/render/project/src"
