[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[theme]
base = "dark"
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1b1f2a"
textColor = "#e5e7eb"

